(require 'ert)

(require 'scxml-elements)

(ert-deftest scxml--element-factory-test-scxml ()
  (let* ((attribs '((initial . "test-initial")
                    (test-property . "anything")))
         (element (scxml--element-factory 'scxml attribs)))
    (should (equal (scxml-element-name element)
                   nil))
    (should (equal (scxml-element-initial element)
                   "test-initial"))
    (should (equal (scxml-get-attrib element 'test-property)
                   "anything"))
    (should (eq (scxml-num-attrib element)
                1))))

(ert-deftest scxml--element-factory-test-state ()
  (let* ((attribs '((id . "test-id")
                    (anything . "else")))
         (element (scxml--element-factory 'state attribs)))
    (should (equal (scxml-element-id element)
                   "test-id"))
    (should (equal (scxml-element-initial element)
                   nil))
    (should (equal (scxml-get-attrib element 'anything)
                   "else"))
    (should (eq (scxml-num-attrib element)
                1))))

(ert-deftest scxml--element-factory-test-final ()
  )
(ert-deftest scxml--element-factory-test-initial ()
  )
(ert-deftest scxml--element-factory-test-parallel ()
  )
(ert-deftest scxml--element-factory-test-transition ()
  )
